controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



errors:
    path: app_error
    # path: /error
    # # controller: App\Controller\ErrorController::index